### ISSUE TITLE
unable to load checkpoints

### ISSUE THREAD

**Issue by tamdan17** [AwesomeLemon/ENCAS#1]
I ran NAT with better hyperparameters (for ENCAS). When executing line number 198 in file nat_run_many.py, it pointed to after_search/average_weights.py and error appeared on line 10. The checkpoint_paths created on line 8 are non-existent (iters folder does not exist) so the execution of load at line 10 failed.

![image](https://user-images.githubusercontent.com/109652477/179921539-0e9501ad-ae13-458a-b59a-61635e564057.png)

![image](https://user-images.githubusercontent.com/109652477/179921092-93055732-aa0b-4ed7-91ae-ea526d12f82c.png)

How can I fix this?
Hope you reply soon.

**Comment by AwesomeLemon** [comment]
Hi,

This is the code for doing SWA (i.e. averaging the weights of the checkpoints that were created when running NAT). If these checkpoints don't exist, something went wrong in NAT. 
Could you share the "_log.txt" file? And tell me what command you ran?
For reference, here's how the folder structure should look like for a successful run: https://surfdrive.surf.nl/files/index.php/s/p53yWOhZ5g2UXyc?path=%2Fcifar10_r0_alpha_sep%2Fsearch_algo%3Ansga3!subset_selector%3Areference%2F0

**Comment by tamdan17** [comment]
I really appreciate you replying so quickly.

I ran the command `python nat_run_many.py --config configs/cifar10_r0_alpha_sep.yml`

And [here](https://drive.google.com/drive/folders/1PqnaCkSTKW2uNcsXfgFFhpcf779772Jz?usp=sharing) is the folder that contains my _log.txt. Its structure has no iter_xx folders. 

Hope you reply soon.

**Comment by AwesomeLemon** [comment]
Thanks for providing the data. 
As I suspected, SWA doesn't work because NAT failed to do anything, and so produced no checkpoints for SWA to work on (so the error is not in the place where you originally suspected).

In the log file in the folder that you provided, the error points to the ``_train`` function, so the code fails during training (or even before it). Since the error is so general (BrokenProcessPool), it's pretty hard for me to say what's going wrong...

Could you check that you can work with your GPU from pytorch? I'd suggest activating the conda environment you've created for this project, running python interpreter, and trying to send a tensor to CUDA (e.g. ``torch.ones((2, 2)).cuda()``). Does that work?

Also, just to be sure: have you followed all the steps in the Readme file?

I would also suggest adding ``print`` statements in various places of ``_train`` and ``_train_one_supernetwork_stateless`` functions to debug where exactly the failure occurs.
